config/routes.rb
Portfolio::Application.routes.draw do

  get '/sign_up' => "users#new", :as => "signup"
  resources :users, :only => [:create]

  get '/log_in' => "sessions#new", :as => "log_in"
  resources :sessions, :only => [:create]

  resources :blog, :only => [:index, :show]

  namespace :admin do 
    resources :posts
    resources :projects
  end

  root :to => 'blog#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :preview, :title

  validates :title, :content, presence: true


end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :title, :content

  validates :title, :content, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessible :email, :password, :password_confirmation

  attr_accessor :password

  before_save :encrypt_password

  validates :email, uniqueness: true, presence: true
  validates :password, presence: true, confirmation: true, on: :create

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  private

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def password_encrypt(password, salt)
    BCrypt::Engine.hash_secret(password, password_salt)
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.attributes = params[:post]
    if @post.save
      flash[:notice] = "Post Saved Successfully"
      redirect_to admin_posts_path
    else
      render 'edit'
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params[:post])
    if @post.save
      flash[:notice] = "Post Created Successfully"
      redirect_to admin_posts_path
    else
      render 'new'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:notice] = "Post Deleted Successfully"
      redirect_to admin_posts_path
    end
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])
    if @project.save
      flash[:notice] = "Project Created Successfully"
      redirect_to admin_projects_path
    else
      render 'new'
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    @project.attributes = params[:project]
    if @project.save
      flash[:notice] = "Project Updated Successfully"
      redirect_to admin_projects_path
    else
      render 'edit'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    if @project.destroy
      flash[:notice] = "Project Deleted Successfully"
      redirect_to admin_projects_path
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController


  def index
    @posts = Post.order('created_at DESC').all
  end

  def show
    @post = Post.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new; end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged In"
    else
      flash.now.alert = "Email or password invalid."
      render :new
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, notice: "Signed up"
    else
      render :new
    end
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/posts/_form.html.erb
<%= form_for [:admin, @post] do |f| %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </p>
  <%= f.submit %> or
  <%= link_to "Cancel", admin_posts_path %>
<% end %>

app/views/admin/posts/create.html.erb
<h1>Admin::Posts#create</h1>
<p>Find me in app/views/admin/posts/create.html.erb</p>

app/views/admin/posts/destroy.html.erb
<h1>Admin::Posts#destroy</h1>
<p>Find me in app/views/admin/posts/destroy.html.erb</p>

app/views/admin/posts/edit.html.erb
<h1>Edit Post - <%= @post.title %></h1>
<%= render 'form' %>

app/views/admin/posts/index.html.erb
<h1>Posts</h1>
<%= link_to "New Post", new_admin_post_path %>
<table>
  <thead>
    <tr>
      <th>Post Title</th>
      <th>Tasks</th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td>
          <%= link_to "Edit", edit_admin_post_path(post) %> | 
          <%= link_to "Delete", admin_post_path(post), method: :delete, confirm: "Are you sure?" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form' %>

app/views/admin/posts/show.html.erb
<h1>Admin::Posts#show</h1>
<p>Find me in app/views/admin/posts/show.html.erb</p>

app/views/admin/posts/update.html.erb
<h1>Admin::Posts#update</h1>
<p>Find me in app/views/admin/posts/update.html.erb</p>

app/views/admin/projects/_form.html.erb
<%= form_for [:admin, @project] do |f| %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </p>
  <%= f.submit %> or <%= link_to "Cancel", admin_projects_path %>

<% end %>

app/views/admin/projects/edit.html.erb
<h1>Edit Project - <%= @project.title %></h1>
<%= render 'form' %>

app/views/admin/projects/index.html.erb
<h1>Projects</h1>
<%= link_to "New Project", new_admin_project_path %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td>
          <%= link_to "Edit", edit_admin_project_path(project) %> |
          <%= link_to "Delete", admin_project_path(project), method: delete %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/projects/new.html.erb
<h1>New Project</h1>
<%= render 'form' %>

app/views/blog/_form.html.erb
<p>
  <%=  f.label :title %><br />
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label :content, "Blog Entry" %><br />
  <%= f.text_area :content, rows: 6, cols: 40 %>
</p>
<div class='actions'>
  <%=  f.submit  %>
  <%=  link_to "Cancel", blog_path(@post) %>
</div>

app/views/blog/edit.html.erb
<%= form_for :post, :url => blog_path(@post), :html => {:method => :put} do |f| %>
  <%= render partial: 'form', {locals: {f: f}} %>
<% end %>

app/views/blog/index.html.erb
<% @posts.each do |post| %>
   <h1><%= link_to post.title, blog_url(post) %></h1>
   <div class='post'>
     <%=  post.content %>
   </div>
   <div class='post_footer'>
     Created: <%=  post.created_at.strftime('%m/%d/%Y %H:%M') %>
   </div>
<% end %>

app/views/blog/new.html.erb
<%= form_for :post, url: blog_index_path, html: {method: :post} do |f| %>
  <%= render :partial => 'form', :locals => {f: f}   %>
<% end %>

app/views/blog/show.html.erb
<h1><%=  @post.title %></h1>
<div class='post'>
  <%=  @post.content %>
</div>
<div class='post_footer'>
  <%=  @post.created_at.strftime('%m/%d/%Y %H:%M') %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
    <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </p>
    <p>
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </p>
    <p>
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </p>
    <p class="button"><%= f.submit %></p>
<% end %>